"use client";
import { Geist, Geist_Mono } from "next/font/google";
import { Salsa } from "next/font/google";
import "./globals.css";
import { createTheme, ThemeProvider } from "@mui/material";

// const geistSans = Jersey_15({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
//   weight: "400",
// });

// const geistMono = Jersey_15({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
//   weight: "400",
// });

const jerseyFont = Salsa({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-jersey", // CSS variable
});

const theme = createTheme({
  typography: {
    fontFamily: "var(--font-jersey), sans-serif",
    fontSize: 16,
  },
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jerseyFont.variable}>
        <ThemeProvider theme={theme}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
